global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bill_rag_app"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: /metrics

  - job_name: "milvus"
    static_configs:
      - targets: ["milvus-standalone:9091"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
